import Pkg
# Pkg.add("EzXML")
# Pkg.add("JSON")
# Pkg.add("JSON3")
# Pkg.add("DataFrames")
# Pkg.add("JSONTables")
# Pkg.add("Flatten")
# Pkg.add("StructTypes")
# Pkg.add("Plots")
# Pkg.add("CSV")
# Pkg.add("PlotlyJS")
# Pkg.add("Statistics")
# Pkg.add("HypothesisTests")
# Pkg.add("Distributions")
#Pkg.add("GeometricFlux")
# Pkg.add("Graphs")
# Pkg.add("GraphPlot")
Pkg.add("MetaGraphsNext")